"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { useForm } from "react-hook-form";
import { saveEmployee } from "../actions";
import { employeeSchema, type EmployeeFormData } from "../schemas";
import type { Department, Designation, Employee, Organization } from "../types";

export function EmployeeForm({ employee, organizations, departments, designations, managers }: { employee?: Employee; organizations: Organization[]; departments: Department[]; designations: Designation[]; managers: Pick<Employee, "id" | "first_name" | "last_name" | "employee_code">[] }) {
  const router = useRouter(); const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<EmployeeFormData>({ resolver: zodResolver(employeeSchema), defaultValues: employee ? { ...employee, phone: employee.phone ?? "", date_of_birth: employee.date_of_birth ?? "", gender: (employee.gender ?? undefined) as EmployeeFormData["gender"], manager_id: employee.manager_id ?? "" } : { employment_type: "FULL_TIME", status: "ACTIVE", manager_id: "" } });
  async function submit(values: EmployeeFormData) { const result = await saveEmployee(values, employee?.id); if (!result.success) { window.alert(result.error); return; } router.push(`/people/employees${employee ? `/${employee.id}` : ""}`); router.refresh(); }
  const field = (name: keyof EmployeeFormData) => errors[name]?.message;
  return <form onSubmit={handleSubmit(submit)} className="space-y-8"><FormSection title="Identity"><div className="grid gap-5 sm:grid-cols-2"><Input label="First name" error={field("first_name")} {...register("first_name")} /><Input label="Last name" error={field("last_name")} {...register("last_name")} /><Input label="Work email" type="email" error={field("email")} {...register("email")} /><Input label="Employee code" error={field("employee_code")} {...register("employee_code")} /><Input label="Phone" {...register("phone")} /><Input label="Date of birth" type="date" {...register("date_of_birth")} /><Select label="Gender" {...register("gender")}><option value="">Select gender</option><option value="MALE">Male</option><option value="FEMALE">Female</option><option value="NON_BINARY">Non-binary</option><option value="PREFER_NOT_TO_SAY">Prefer not to say</option></Select></div></FormSection><FormSection title="Employment"><div className="grid gap-5 sm:grid-cols-2"><Select label="Organization" error={field("organization_id")} {...register("organization_id")}><option value="">Select organization</option>{organizations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Input label="Date of joining" type="date" error={field("date_of_joining")} {...register("date_of_joining")} /><Select label="Department" error={field("department_id")} {...register("department_id")}><option value="">Select department</option>{departments.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select label="Designation" error={field("designation_id")} {...register("designation_id")}><option value="">Select designation</option>{designations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select label="Employment type" error={field("employment_type")} {...register("employment_type")}><option value="FULL_TIME">Full time</option><option value="PART_TIME">Part time</option><option value="CONTRACT">Contract</option><option value="INTERN">Intern</option></Select><Select label="Status" error={field("status")} {...register("status")}><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option><option value="ON_LEAVE">On leave</option></Select><Select label="Manager" {...register("manager_id")}><option value="">No manager</option>{managers.filter((item) => item.id !== employee?.id).map((item) => <option key={item.id} value={item.id}>{item.first_name} {item.last_name} ({item.employee_code})</option>)}</Select></div></FormSection><div className="flex justify-end gap-3"><button type="button" onClick={() => router.back()} className="h-10 rounded-md border px-4 text-sm font-semibold text-slate-600">Cancel</button><button disabled={isSubmitting} type="submit" className="h-10 rounded-md bg-[var(--navy)] px-5 text-sm font-semibold text-white disabled:opacity-60">{isSubmitting ? "Saving..." : employee ? "Save employee" : "Create employee"}</button></div></form>;
}

function FormSection({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2 className="mb-4 text-base font-bold text-[var(--navy)]">{title}</h2>{children}</section>; }
const Input = ({ label, error, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string; error?: string }) => <label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-600">{label}</span><input {...props} className="h-10 w-full rounded-md border bg-white px-3 text-sm outline-none focus:border-[var(--teal)]" />{error && <span className="mt-1 block text-xs text-[#a34836]">{error}</span>}</label>;
const Select = ({ label, error, children, ...props }: React.SelectHTMLAttributes<HTMLSelectElement> & { label: string; error?: string }) => <label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-600">{label}</span><select {...props} className="h-10 w-full rounded-md border bg-white px-3 text-sm outline-none focus:border-[var(--teal)]">{children}</select>{error && <span className="mt-1 block text-xs text-[#a34836]">{error}</span>}</label>;